version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    network_mode: "bridge"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-creepy_elephant}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dcdb262c-3d8d-42de-b54d-f828c2439e17}
      PGDATA: /data/postgres
    volumes:
       - ./.pg-data:/data/postgres
       - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "6001:5432"
    restart: unless-stopped
